name: trashtrackr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  #unlock camera features
  camera: ^0.11.1
  #firebase core
  firebase_core: ^3.13.0
  #firebase auth
  firebase_auth: ^5.5.3
  #google sign in
  google_sign_in: ^6.3.0
  #firebase storage
  firebase_storage: ^12.4.5
  #firestore storage
  cloud_firestore: ^5.6.7
  #state management
  provider: ^6.1.5
  #unlocks gemini features
  google_generative_ai: ^0.4.7
  #gal is a dart3 plugin for saving images to gallery
  gal: ^2.3.1
  #handles app permission for cameras and storage
  permission_handler: ^12.0.0+1
  card_swiper: ^3.0.1
  rflutter_alert: ^2.0.7
  #loads configuration from .env file
  flutter_dotenv: ^5.2.1
  #google fonts
  google_fonts: ^6.2.1
  #indicates percentage
  percent_indicator: ^4.2.5
  #google maps
  google_maps_flutter: ^2.12.1
  #location services
  location: ^8.0.0
  #for http requests in google maps
  http: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/map/
    - assets/images/
    - assets/images/badges/
    - assets/images/badges/colored/
    - assets/images/badges/gray/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
