name: trashtrackr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  #unlock camera features
  camera: ^0.11.1
  #unlocks gemini features
  google_generative_ai: ^0.4.7
  #gal is a dart3 plugin for saving images to gallery
  gal: ^2.3.1
  #handles app permission for cameras and storage
  permission_handler: ^12.0.0+1
  card_swiper: ^3.0.1
  rflutter_alert: ^2.0.7
  #loads configuration from .env file
  flutter_dotenv: ^5.2.1
  #google fonts
  google_fonts: ^6.2.1
  #indicates percentage
  percent_indicator: ^4.2.5
  #streak widget
  streakify: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/badges/
    - assets/images/badges/colored/
    - assets/images/badges/gray/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
