name: trashtrackr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  #unlock camera features
  camera: ^0.11.1
  #unlocks gemini features
  google_generative_ai: ^0.4.7
  #gal is a dart3 plugin for saving images to gallery
  gal: ^2.3.1
  card_swiper: ^3.0.1
  rflutter_alert: ^2.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
