enum EcoBadge {
  greenStreaker,
  weekendWarrior,
  barcodeSleuth,
  ecoChampion,
  scannerRookie,
  zeroWasteHero,
  firstToss,
  sortingExpert,
  ecoInfluencer,
  dailyDiligent,
  plasticBuster,
  cleanupCaptain,
  quizMaster,
  trashTrackrOg,
}

const Map<EcoBadge, String> badgePath = {
  EcoBadge.greenStreaker: 'green_streaker.png',
  EcoBadge.weekendWarrior: 'weekend_warrior.png',
  EcoBadge.barcodeSleuth: 'barcode_sleuth.png',
  EcoBadge.ecoChampion: 'eco_champion.png',
  EcoBadge.scannerRookie: 'scanner_rookie.png',
  EcoBadge.zeroWasteHero: 'zero_waste_hero.png',
  EcoBadge.firstToss: 'first_toss.png',
  EcoBadge.sortingExpert: 'sorting_expert.png',
  EcoBadge.ecoInfluencer: 'eco_influencer.png',
  EcoBadge.dailyDiligent: 'daily_diligent.png',
  EcoBadge.plasticBuster: 'plastic_buster.png',
  EcoBadge.cleanupCaptain: 'cleanup_captain.png',
  EcoBadge.quizMaster: 'quiz_master.png',
  EcoBadge.trashTrackrOg: 'trash_trackr_og.png',
};

const Map<EcoBadge, String> badgeTitle = {
  EcoBadge.greenStreaker: 'Green Streaker',
  EcoBadge.weekendWarrior: 'Weekend Warrior',
  EcoBadge.barcodeSleuth: 'Bar code Sleuth',
  EcoBadge.ecoChampion: 'Eco Champion',
  EcoBadge.scannerRookie: 'Scanner Rookie',
  EcoBadge.zeroWasteHero: 'Zero Waste Hero',
  EcoBadge.firstToss: 'First Toss',
  EcoBadge.sortingExpert: 'Sorting Expert',
  EcoBadge.ecoInfluencer: 'Eco Influencer',
  EcoBadge.dailyDiligent: 'Daily Diligent',
  EcoBadge.plasticBuster: 'Plastic Buster',
  EcoBadge.cleanupCaptain: 'Clean-up Captain',
  EcoBadge.quizMaster: 'Quiz Master',
  EcoBadge.trashTrackrOg: 'TrashTrackr OG',
};

const Map<EcoBadge, String> badgeDesc = {
  EcoBadge.greenStreaker: 'Reach a 7-day streak',
  EcoBadge.weekendWarrior: 'Use the app on both a Saturday and a Sunday',
  EcoBadge.barcodeSleuth: 'Scan 10 product barcodes',
  EcoBadge.ecoChampion: 'Hit a 30-day milestone',
  EcoBadge.scannerRookie: 'Classify 10 items correctly',
  EcoBadge.zeroWasteHero: 'Log a waste-free day',
  EcoBadge.firstToss: 'Classify your first item correctly',
  EcoBadge.sortingExpert: 'Get 100 correct classifications',
  EcoBadge.ecoInfluencer: 'Share the app or share one of your achievements',
  EcoBadge.dailyDiligent: 'Use the app 5 days in a row',
  EcoBadge.plasticBuster: 'Properly dispose of 20 plastic items',
  EcoBadge.cleanupCaptain: 'Join or log a local clean-up activity',
  EcoBadge.quizMaster: 'Ace 10 eco quizzes with perfect scores',
  EcoBadge.trashTrackrOg: 'Install and use the app in its first month',
};

const Map<int, EcoBadge> badgeId = {
  1: EcoBadge.greenStreaker,
  2: EcoBadge.weekendWarrior,
  3: EcoBadge.barcodeSleuth,
  4: EcoBadge.ecoChampion,
  5: EcoBadge.scannerRookie,
  6: EcoBadge.zeroWasteHero,
  7: EcoBadge.firstToss,
  8: EcoBadge.sortingExpert,
  9: EcoBadge.ecoInfluencer,
  10: EcoBadge.dailyDiligent,
  11: EcoBadge.plasticBuster,
  12: EcoBadge.cleanupCaptain,
  13: EcoBadge.quizMaster,
  14: EcoBadge.trashTrackrOg,
};